/* ============================================================
   Daniel Polo — Blog list + homepage preview
   Reads posts/index.json (generated by tools/reindex.mjs) and renders:
     #postList    → full searchable/filterable/sortable list (blog.html)
     #blogPreview → latest 3 posts (index.html)
   Localised text is read from window.I18N; re-renders on language switch.
   No markdown parsing here (titles/excerpts come from the manifest).
   ============================================================ */
(function () {
  "use strict";

  var listEl = document.getElementById("postList");
  var previewEl = document.getElementById("blogPreview");
  if (!listEl && !previewEl) return;

  var LANGS = { ja: 1, zh: 1, en: 1 };

  function lang() {
    var l = document.documentElement.getAttribute("lang");
    if (!l) { try { l = localStorage.getItem("dp-lang"); } catch (e) {} }
    return LANGS[l] ? l : "en";
  }
  function t(key) {
    var L = window.I18N || {};
    var d = L[lang()] || L.en || {};
    return d[key] != null ? d[key] : (L.en && L.en[key] != null ? L.en[key] : key);
  }
  function pick(field) {
    // field is {en,ja,zh}; fall back to en then to any present value
    if (field == null) return "";
    if (typeof field === "string") return field;
    return field[lang()] || field.en || field[Object.keys(field)[0]] || "";
  }
  function fmtDate(iso) {
    try { return new Date(iso + "T00:00:00").toLocaleDateString(lang(), { year: "numeric", month: "short", day: "numeric" }); }
    catch (e) { return iso; }
  }
  function el(tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html != null) n.innerHTML = html;
    return n;
  }
  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; }); }

  var ARROW = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" style="width:15px;height:15px"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';

  var posts = [];

  /* ---------- Homepage preview (latest 3) ---------- */
  function renderPreview() {
    if (!previewEl) return;
    var latest = posts.slice().sort(function (a, b) { return b.date < a.date ? -1 : 1; }).slice(0, 3);
    previewEl.innerHTML = "";
    latest.forEach(function (p) {
      var a = el("a", "bp-card");
      a.href = "post.html?slug=" + encodeURIComponent(p.slug);
      a.appendChild(el("h4", null, esc(pick(p.title))));
      a.appendChild(el("p", "bp-excerpt", esc(pick(p.excerpt))));
      a.appendChild(el("span", "pr-date", esc(fmtDate(p.date))));
      previewEl.appendChild(a);
    });
  }

  /* ---------- Full list (blog.html) ---------- */
  var PAGE_SIZE = 10;            // X posts per page before the paginator kicks in
  var state = { q: "", topic: "", vendor: "", sort: "newest", page: 1 };  // topic/vendor = normalised keys ("" = all)

  // Facets (themes + maker) derived from posts. Themes are FREE tags that drift in casing
  // ("AI safety" vs "AI Safety") and pile up a long singleton tail, so we group case-insensitively
  // into ONE entry per value and show the dominant casing — self-healing as posts are added. Counts
  // are CROSS-FILTERED: each dropdown's numbers reflect the OTHER active filters + the search.
  function norm(v) { return String(v == null ? "" : v).trim().toLowerCase(); }
  function themesOf(p) { return p.themes || []; }
  function vendorOf(p) { return p.vendor ? [p.vendor] : []; }

  var FACETS = [
    { key: "topic",  labelKey: "blog.filterTopic", valuesOf: themesOf },
    { key: "vendor", labelKey: "blog.filterMaker", valuesOf: vendorOf }
  ];

  function facetModel(list, valuesOf) {
    var map = {};
    list.forEach(function (p) {
      var seen = {};
      valuesOf(p).forEach(function (raw) {
        var k = norm(raw);
        if (!k || seen[k]) return;          // count each post once per value
        seen[k] = 1;
        if (!map[k]) map[k] = { count: 0, variants: {} };
        map[k].count++;
        map[k].variants[raw] = (map[k].variants[raw] || 0) + 1;
      });
    });
    return Object.keys(map).map(function (k) {
      var m = map[k], label = k, best = -1;
      Object.keys(m.variants).forEach(function (v) { if (m.variants[v] > best) { best = m.variants[v]; label = v; } });
      return { key: k, label: label, count: m.count };
    }).sort(function (a, b) { return b.count - a.count || (a.label.toLowerCase() < b.label.toLowerCase() ? -1 : 1); });
  }

  // Display label for a selection (values are not translated; "All" is localised).
  function facetLabel(rows, key) {
    if (!key) return t("blog.all");
    for (var i = 0; i < rows.length; i++) if (rows[i].key === key) return rows[i].label;
    return t("blog.all");
  }

  /* ---- predicates shared by the list and the cross-filtered counts ---- */
  function matchSearch(p) {
    var q = state.q.trim().toLowerCase();
    if (!q) return true;
    var hay = (pick(p.title) + " " + pick(p.excerpt) + " " + (p.themes || []).join(" ") + " " + (p.vendor || "")).toLowerCase();
    return hay.indexOf(q) >= 0;
  }
  function matchFacet(p, key) {
    var sel = state[key];
    if (!sel) return true;
    if (key === "vendor") return norm(p.vendor) === sel;
    return themesOf(p).some(function (th) { return norm(th) === sel; });   // "topic"
  }
  // Posts passing the search + every facet EXCEPT `key` — the set its option counts are taken over.
  function subsetExcept(key) {
    return posts.filter(function (p) {
      if (!matchSearch(p)) return false;
      for (var i = 0; i < FACETS.length; i++) { var f = FACETS[i].key; if (f !== key && !matchFacet(p, f)) return false; }
      return true;
    });
  }

  // Close every open facet dropdown except `keep` (one open at a time + outside-click close).
  function closeFacets(keep) {
    var open = document.querySelectorAll(".topic-filter.open");
    for (var i = 0; i < open.length; i++) if (open[i] !== keep && open[i]._close) open[i]._close();
  }
  function enabledOpts(menu) {
    return Array.prototype.slice.call(menu.querySelectorAll(".tf-opt")).filter(function (o) { return !o.disabled; });
  }

  // Recompute cross-filtered counts for every facet and update its menu IN PLACE — no rebuild, so
  // the search field keeps focus. "All" shows the subset size; a zero-count option is disabled
  // unless it is "All" or the current selection (so you can always switch back).
  function refreshFacets() {
    FACETS.forEach(function (f) {
      var wrap = document.querySelector('.topic-filter[data-facet="' + f.key + '"]');
      if (!wrap) return;
      var subset = subsetExcept(f.key), counts = {};
      facetModel(subset, f.valuesOf).forEach(function (r) { counts[r.key] = r.count; });
      var opts = wrap.querySelectorAll(".tf-opt");
      for (var i = 0; i < opts.length; i++) {
        var o = opts[i], k = o.getAttribute("data-key"), sel = state[f.key] === k;
        var n = k === "" ? subset.length : (counts[k] || 0);
        var cs = o.querySelector(".tf-count"); if (cs) cs.textContent = n;
        o.disabled = (n === 0 && k !== "" && !sel);
        o.className = "tf-opt" + (sel ? " active" : "");
        o.setAttribute("aria-selected", sel ? "true" : "false");
      }
    });
  }

  // Controls are built once per load / language switch — NOT on every keystroke, so the search
  // field keeps focus while typing. Filter/search changes refresh the cross-filtered counts in place.
  function buildControls() {
    var bar = document.getElementById("blogControls");
    if (!bar) return;
    bar.innerHTML = "";

    var search = el("input", "blog-search");
    search.type = "search";
    search.value = state.q;
    search.placeholder = t("blog.search");
    search.addEventListener("input", function () { state.q = search.value; state.page = 1; renderList(); refreshFacets(); });
    bar.appendChild(search);

    FACETS.forEach(function (f) {
      var universe = facetModel(posts, f.valuesOf);   // stable option list (every value)
      if (universe.length) bar.appendChild(buildFacetFilter(f, universe));
    });

    var sort = el("select", "blog-sort");
    sort.innerHTML = '<option value="newest">' + esc(t("blog.sortNewest")) + '</option><option value="oldest">' + esc(t("blog.sortOldest")) + "</option>";
    sort.value = state.sort;
    sort.addEventListener("change", function () { state.sort = sort.value; state.page = 1; renderList(); });
    bar.appendChild(sort);

    refreshFacets();   // initial counts (honours any pre-existing filter, e.g. after a language switch)
  }

  // Compact single-select dropdown for one facet. The option list is the full universe (stable);
  // counts + disabled state are filled by refreshFacets. Keyboard (Arrow/Enter/Esc) + outside-click.
  function buildFacetFilter(f, rows) {
    var key = f.key;
    var wrap = el("div", "topic-filter");
    wrap.setAttribute("data-facet", key);

    var btn = el("button", "topic-btn");
    btn.type = "button";
    btn.setAttribute("aria-haspopup", "listbox");
    btn.setAttribute("aria-expanded", "false");
    btn.innerHTML = '<span class="tf-label">' + esc(t(f.labelKey)) + '</span>' +
      '<span class="tf-value">' + esc(facetLabel(rows, state[key])) + '</span>' +
      '<svg class="tf-caret" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 9l6 6 6-6"/></svg>';
    wrap.appendChild(btn);

    var menu = el("div", "topic-menu");
    menu.setAttribute("role", "listbox");
    menu.hidden = true;
    wrap.appendChild(menu);

    function setValue() { var v = wrap.querySelector(".tf-value"); if (v) v.textContent = facetLabel(rows, state[key]); }
    function open() { closeFacets(wrap); menu.hidden = false; btn.setAttribute("aria-expanded", "true"); wrap.className = "topic-filter open"; }
    function close() { menu.hidden = true; btn.setAttribute("aria-expanded", "false"); wrap.className = "topic-filter"; }
    wrap._close = close;   // reached by closeFacets + the document-level outside-click handler

    function addOption(optKey, label) {
      var o = el("button", "tf-opt");
      o.type = "button";
      o.setAttribute("role", "option");
      o.setAttribute("data-key", optKey);
      o.innerHTML = '<span class="tf-opt-label">' + esc(label) + '</span><span class="tf-count"></span>';
      o.addEventListener("click", function () {
        if (o.disabled) return;
        state[key] = optKey; state.page = 1;
        close(); setValue(); renderList(); refreshFacets(); btn.focus();
      });
      menu.appendChild(o);
    }

    addOption("", t("blog.all"));
    rows.forEach(function (r) { addOption(r.key, r.label); });

    btn.addEventListener("click", function () { menu.hidden ? open() : close(); });
    btn.addEventListener("keydown", function (e) {
      if (e.key === "ArrowDown" || e.key === "Enter" || e.key === " ") {
        e.preventDefault(); open();
        var first = menu.querySelector(".tf-opt.active") || enabledOpts(menu)[0];
        if (first) first.focus();
      }
    });
    menu.addEventListener("keydown", function (e) {
      var opts = enabledOpts(menu), i = opts.indexOf(document.activeElement);
      if (e.key === "ArrowDown") { e.preventDefault(); (opts[i + 1] || opts[0]).focus(); }
      else if (e.key === "ArrowUp") { e.preventDefault(); (opts[i - 1] || opts[opts.length - 1]).focus(); }
      else if (e.key === "Escape") { e.preventDefault(); close(); btn.focus(); }
    });

    return wrap;
  }

  function filteredRows() {
    var rows = posts.filter(function (p) {
      return matchSearch(p) && matchFacet(p, "topic") && matchFacet(p, "vendor");
    });
    rows.sort(function (a, b) {
      if (a.date === b.date) return 0;
      return (state.sort === "oldest" ? (a.date < b.date) : (a.date > b.date)) ? -1 : 1;
    });
    return rows;
  }

  function renderList() {
    if (!listEl) return;

    var rows = filteredRows();
    var pages = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
    if (state.page > pages) state.page = pages;
    if (state.page < 1) state.page = 1;
    var start = (state.page - 1) * PAGE_SIZE;
    var pageRows = rows.slice(start, start + PAGE_SIZE);

    listEl.innerHTML = "";
    if (!rows.length) {
      listEl.appendChild(el("div", "blog-state", esc(t("blog.empty"))));
      renderPager(1);
      return;
    }
    pageRows.forEach(function (p) {
      var a = el("a", "post-row");
      a.href = "post.html?slug=" + encodeURIComponent(p.slug);

      var date = el("span", "pr-date", esc(fmtDate(p.date)));

      var main = el("span", "pr-main");
      main.appendChild(el("h4", null, esc(pick(p.title)) + " <span class=\"ext\">↗</span>"));
      main.appendChild(el("div", "pr-excerpt", esc(pick(p.excerpt))));
      var meta = el("div", "pr-meta");
      (p.themes || []).forEach(function (th) { meta.appendChild(el("span", "ptheme", esc(th))); });
      main.appendChild(meta);

      // grid is "1fr auto": main on the left, date on the right (date moves on top on mobile)
      a.appendChild(main);
      a.appendChild(date);
      listEl.appendChild(a);
    });
    renderPager(pages);
  }

  // Compact page window: 1 … (cur-1) cur (cur+1) … last
  function pageWindow(cur, total) {
    if (total <= 7) {
      var all = [];
      for (var i = 1; i <= total; i++) all.push(i);
      return all;
    }
    var out = [1];
    var lo = Math.max(2, cur - 1), hi = Math.min(total - 1, cur + 1);
    if (lo > 2) out.push("…");
    for (var j = lo; j <= hi; j++) out.push(j);
    if (hi < total - 1) out.push("…");
    out.push(total);
    return out;
  }

  function goTo(page) {
    state.page = page;
    renderList();
    var top = document.getElementById("top");
    if (top && top.scrollIntoView) top.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  function renderPager(pages) {
    var pager = document.getElementById("blogPager");
    if (!pager) return;
    pager.innerHTML = "";
    if (pages <= 1) return;     // single page → no paginator

    var prev = el("button", "pg-btn" + (state.page <= 1 ? " disabled" : ""), esc(t("blog.prev")));
    prev.type = "button";
    if (state.page > 1) prev.addEventListener("click", function () { goTo(state.page - 1); });
    pager.appendChild(prev);

    pageWindow(state.page, pages).forEach(function (n) {
      if (n === "…") { pager.appendChild(el("span", "pg-gap", "…")); return; }
      var b = el("button", "pg-num" + (n === state.page ? " active" : ""), String(n));
      b.type = "button";
      b.setAttribute("aria-current", n === state.page ? "page" : "false");
      b.addEventListener("click", function () { goTo(n); });
      pager.appendChild(b);
    });

    var next = el("button", "pg-btn" + (state.page >= pages ? " disabled" : ""), esc(t("blog.next")));
    next.type = "button";
    if (state.page < pages) next.addEventListener("click", function () { goTo(state.page + 1); });
    pager.appendChild(next);
  }

  function draw() { buildControls(); renderList(); renderPreview(); }

  /* ---------- Load + language switching ---------- */
  fetch("posts/index.json", { cache: "no-cache" })
    .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
    .then(function (data) { posts = (data && data.posts) || []; draw(); })
    .catch(function () {
      if (listEl) { listEl.innerHTML = ""; listEl.appendChild(el("div", "blog-state", esc(t("blog.empty")))); }
    });

  document.querySelectorAll("#lang button").forEach(function (b) {
    b.addEventListener("click", function () { setTimeout(draw, 0); });
  });

  // One document-level listener (not re-bound per control rebuild) closes any open facet
  // dropdown on a click outside it.
  document.addEventListener("click", function (e) {
    var open = document.querySelectorAll(".topic-filter.open");
    for (var i = 0; i < open.length; i++) if (!open[i].contains(e.target) && open[i]._close) open[i]._close();
  });
})();
